
##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON =  ranlib

#
# If you need any extra DEFINES, put them here

override DEFINE +=

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#

LOCAL_LIBS =  


# 
# SRC: lists all source files
SRC = Permutation ConfigFile BalancedTree VectorEnumerator gmp_boost_pool_allocator


# 
# MAIN lists all source files with main function:

MAIN = mask


## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



