
##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON = Alphabet general Elt  ranlib

#
# If you need any extra DEFINES, put them here

override DEFINE +=

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#

LOCAL_LIBS = -L/lib/ -lgmpxx -lgmp


# 
# SRC: lists all source files
SRC = GraphConcept GraphType GraphDrawingAttributes Graph GraphRep FSA FSARep RandomFSA


# 
# MAIN lists all source files with main function:

MAIN = test_rand


## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



