
##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON = TheGrigorchukGroup Equation CryptoTripleDecomposition CryptoKL CryptoAAG CryptoShftConj FreeGroup Group SbgpFG Graph Graphics StringSimilarity Maps BraidGroup Alphabet Elt general ranlib

#
# If you need any extra DEFINES, put them here

override DEFINE +=

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#

LOCAL_LIBS =  


# 
# SRC: lists all source files
SRC = 


# 
# MAIN lists all source files with main function:

MAIN = ex_centralizerSbgpFreeGp ex_conjugacySbgpFreeGp ex_drawingSbgpFreeGp ex_normalizerSbgpFreeGp ex_operationsSbgpFreeGp ex_KLKeyGeneration ex_AAGKeyGeneration ex_ShiftConjProtocol ex_generateEqConjWords ex_WordProblemFinPresGroup ex_GraphConcept ex_FreeGroup ex_Map ex_DehornoyForm ex_Word ex_Alphabet ex_FPGroup ex_GraphDrawing ex_Permutation ex_ThRightNF ex_ThLeftNF ex_TripleDecompositionKeyGeneration  ex_TheGrigorchukGroup ex_drawBraid

## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



