
##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON = Alphabet Elt general  ranlib 

#
# If you need any extra DEFINES, put them here

override DEFINE +=

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#

LOCAL_LIBS =  


# 
# SRC: lists all source files
SRC = BraidGroup ThRightNormalForm ThRightNormalForm_uss ThRightNormalForm_sss LinkedBraidStructure DehornoyForm ShortBraidForm ThLeftNormalForm


# 
# MAIN lists all source files with main function:

MAIN = test_rightNF test_leftNF test_deh_form


## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



