
##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON = BraidGroup Alphabet Elt general ranlib

#
# If you need any extra DEFINES, put them here

override DEFINE +=

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#


LOCAL_LIBS = 
LOCAL_INCLUDE = 


# 
# SRC: lists all source files
SRC = AAGKeyGeneration AAGChallengeGeneration LengthAttack_A1 LengthAttack_A2 LengthAttack_A3 MajorDump


# 
# MAIN lists all source files with main function:

MAIN = test_length_attack test_sbgp_attack 

## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



