##
## Authors:Alexei Miasnikov
##
## 
##


##
## DEPEND_ON: list all dependencies here
##

DEPEND_ON = BraidGroup Alphabet Elt general ranlib

#
# If you need any extra DEFINES, put them here

override DEFINE += USE_CBRAID

#
# Set debug level here

# DEBUG =

#
# if you want to pass extra libraries to the linker which are not
# used by default
#


# 
# SRC: lists all source files
SRC = AEProtocol TTPAttack


# 
# MAIN lists all source files with main function:

MAIN = test_TTP 


## All the compiler and linker stuff here:                           
#                                                                    
include ../common.mk                                          



